grpc_server:
  socket_path: /etc/kubeedge/modbus.sock
common:
  name: Modbus-mapper
  version: v1.13.0
  api_version: v1.0.0
  protocol: modbus # TODO add your protocol name
  address: 127.0.0.1
  edgecore_sock: /etc/kubeedge/dmi.sock
