apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-cloud
  labels:
    app: demo-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-cloud
  template:
    metadata:
      labels:
        app: demo-cloud
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/edge
                  operator: DoesNotExist
                - key: node-role.kubernetes.io/agent
                  operator: DoesNotExist
      containers:
        - name: demo-cloud
          image: cloud_demo:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: demo-cloud
spec:
  type: NodePort
  ports:
  - port: 8001
    nodePort: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: demo-cloud