apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kubeedge-web-app
  name: kubeedge-web-app
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: kubeedge-web-app
  template:
    metadata:
      labels:
        k8s-app: kubeedge-web-app
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      hostNetwork: true
      containers:
      - name: kubeedge-web-app
        image: kubeedge/kubeedge-web-app:v2.6
        imagePullPolicy: IfNotPresent
