apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-webui
  labels:
    app: temperature-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature-webui
  template:
    metadata:
      labels:
        app: temperature-webui
    spec:
      hostNetwork: true
      nodeName: kind-control-plane # 1. replace the nodeName with your edge node name
      containers:
        - name: temperature-webui
          image: temperature-webui:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
# device-access-rbac
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: device-access-role
rules:
- apiGroups: ["devices.kubeedge.io"]
  resources: ["devices"]  
  verbs: ["get", "list", "watch"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: device-access-binding
subjects:
- kind: ServiceAccount
  name: default           
  namespace: default      
roleRef:
  kind: ClusterRole
  name: device-access-role
  apiGroup: rbac.authorization.k8s.io