apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-sensor-mapper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapper
  template:
    metadata:
      labels:
        app: mapper
    spec:
      nodeName: kind-worker # 1. replace the nodeName with your edge node name
      containers:
        - name: mapper
          volumeMounts: # Required, mapper need to communicate with grpcclient and get the config
            - name: test-volume
              mountPath: /etc/kubeedge
            - name: config
              mountPath: /tmp
          # env: # Not Required, this field is used to mount the user database key
          #   - name: TOKEN
          #     valueFrom:
          #       secretKeyRef:
          #         name: mysecret
          #         key: token
          image: temperature-mapper:v1.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          command: [ "/kubeedge/main" ]
          args: [ "--config-file=/tmp/config.yaml","--v=5" ] 
      volumes:
        - name: test-volume
          hostPath:
            path: /etc/kubeedge
            type: Directory
        - name: config
          configMap:
            name: cm-mapper
            items:
              - key: configData
                path: config.yaml



---
apiVersion: v1
kind: Service
metadata:
  name: mapper-service
spec:
  type: NodePort
  selector:
    app: mapper
  ports:
    - name: http
      protocol: TCP
      port: 7777           
      targetPort: 7777   
      nodePort: 30077    
 
